---
- name: install subscription-manager
  package:
    name: subscription-manager
    state: present

- name: Register to access.redhat.com 
  redhat_subscription:
    state: present
    force_register: "{{ subscription_manager_force_register | default(omit) }}"
    username: "{{ subscription_manager.user }}"
    password: "{{ subscription_manager.password }}"
    pool_ids: "{{ subscription_manager_pool_id }}"
    server_proxy_hostname: "{{ subscription_manager.proxy_hostname | default(omit) }}"
    server_proxy_password: "{{ subscription_manager.proxy_password | default(omit) }}"
    server_proxy_port: "{{ subscription_manager.proxy_port | default(omit) }}"
    server_proxy_user: "{{ subscription_manager.proxy_user | default(omit) }}"
  when: subscription_manager_pool_id is defined

- name: "Enable {{ subscription_manager_enabled_repos }} repositories"
  rhsm_repository:
    name: "{{ item }}"
    state: enabled
  with_items: "{{ subscription_manager_enabled_repos }}"
  when: subscription_manager_enabled_repos is defined

- name: "Disable {{ subscription_manager_disabled_repos }} repositories"
  rhsm_repository:
    name: "{{ item }}"
    state: disabled
  with_items: "{{ subscription_manager_disabled_repos }}"
  when: subscription_manager_disabled_repos is defined
